import type { WordDTO } from "@keylish/shared";
import seed from "./seed-vocabulary.json";

interface RawSeedWord {
  en: string;
  vi: string;
  topic?: string;
  pos?: string;
  level?: string;
  frequency?: number;
}

/** Bundled offline seed (generated by scripts/build-vocab.mjs). */
export const SEED_VOCABULARY: WordDTO[] = (seed.words as RawSeedWord[]).map((w) => ({
  id: `seed-${w.en}`,
  en: w.en,
  vi: w.vi,
  topic: w.topic,
  pos: w.pos,
  level: w.level as WordDTO["level"],
  frequency: w.frequency ?? 0,
  source: "seed",
}));

export const SEED_TOPICS: string[] = Array.from(
  new Set(SEED_VOCABULARY.map((w) => w.topic).filter(Boolean) as string[])
);

export const SEED_LEVELS = ["A1", "A2", "B1", "B2", "C1", "C2"] as const;
